In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
get_ipython().run_line_magic('matplotlib', 'inline')


In [2]:
from sklearn.datasets import load_breast_cancer

In [3]:
#creatine an object
lbc = load_breast_cancer()

In [4]:
lbc.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [5]:
print(lbc['DESCR'])
#WDBC-Malignant : cancerous
#WDBC-Benign : damaged cell but non cancerous


.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry 
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 3 is Mean Radius, f

In [6]:
print(lbc['feature_names'])

['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']


In [7]:
#assigning the value of X and Y

x = pd.DataFrame(lbc['data'], columns=lbc['feature_names'])
y = pd.DataFrame(lbc['target'], columns=['type'])

# Code without PCA

In [8]:
#split into traning and test
from sklearn.model_selection import train_test_split

In [9]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=1234, stratify=y)

In [10]:
# Import Random Forest

from sklearn.ensemble import RandomForestClassifier

In [11]:
rf = RandomForestClassifier(random_state=1234)

In [12]:
rf.fit(x_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=1234,
                       verbose=0, warm_start=False)

In [13]:
y_pred = rf.predict(x_test)

In [14]:
#Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [25]:
cm

array([[38,  4],
       [ 0, 72]], dtype=int64)

In [15]:
score = rf.score(x_test, y_test)

In [16]:
score

0.9649122807017544

# Code with PCA implementation

In [17]:
# import standard scaler
from sklearn.preprocessing import StandardScaler

In [18]:
scaler = StandardScaler()

In [19]:
x_scaler = scaler.fit_transform(x)

In [20]:
x_scaler

array([[ 1.09706398, -2.07333501,  1.26993369, ...,  2.29607613,
         2.75062224,  1.93701461],
       [ 1.82982061, -0.35363241,  1.68595471, ...,  1.0870843 ,
        -0.24388967,  0.28118999],
       [ 1.57988811,  0.45618695,  1.56650313, ...,  1.95500035,
         1.152255  ,  0.20139121],
       ...,
       [ 0.70228425,  2.0455738 ,  0.67267578, ...,  0.41406869,
        -1.10454895, -0.31840916],
       [ 1.83834103,  2.33645719,  1.98252415, ...,  2.28998549,
         1.91908301,  2.21963528],
       [-1.80840125,  1.22179204, -1.81438851, ..., -1.74506282,
        -0.04813821, -0.75120669]])

In [21]:
from sklearn.decomposition import PCA

In [22]:
pca = PCA(n_components=3)

In [23]:
x_pca = pca.fit_transform(x_scaler)

In [24]:
x_pca

array([[ 9.19283683,  1.94858328, -1.12316443],
       [ 2.3878018 , -3.7681716 , -0.52929076],
       [ 5.73389628, -1.0751738 , -0.55174748],
       ...,
       [ 1.25617928, -1.90229679,  0.56272977],
       [10.37479406,  1.67201004, -1.87703   ],
       [-5.4752433 , -0.67063648,  1.49044641]])

In [ ]:
#Compare the result

In [26]:
x_train, x_test, y_train, y_test = train_test_split(x_pca,y, test_size=0.2, random_state=1234, stratify=y)

In [27]:
rf1 = RandomForestClassifier(random_state=1234)

In [28]:
rf1.fit(x_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=1234,
                       verbose=0, warm_start=False)

In [29]:
y_pred1 = rf1.predict(x_test)

In [36]:
#Confusion Matrix
from sklearn.metrics import confusion_matrix
cm1 = confusion_matrix(y_test, y_pred1)

In [40]:
cm

array([[38,  4],
       [ 0, 72]], dtype=int64)

In [37]:
cm1

array([[39,  3],
       [ 0, 72]], dtype=int64)

In [38]:
score1 = rf1.score(x_test, y_test)

In [39]:
score1

0.9736842105263158